providers = ["node"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build && echo '✅ Build completed successfully'"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--no-deprecation=punycode"
APP_VERSION = "1.0.0"